### ISSUE TITLE
WebSocket 'TransportError',       description: 400

### ISSUE THREAD

**Issue by JoelCode** [bitbns-official/node-bitbns-api#10]
I wake up today & had type: 'TransportError' description: 400 everywhere, so what's going on?

`
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns QTUM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
network
{
  data: {
    message: 'BitBns ONT/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BCH/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns NEO/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns LTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns TRX/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BCH/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns NEO/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns QTUM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns TRX/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BCH/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns QTUM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns NEO/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns NEO/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns QTUM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns BTC/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
{
  data: {
    message: 'BitBns XLM/INR',
    error: Error: xhr poll error
        at XHR.Transport.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transport.js:68:13)
        at Request.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:131:10)
        at Request.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\node_modules\component-emitter\index.js:133:20)
        at Request.onError (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:313:8)
        at Timeout._onTimeout (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\engine.io-client\lib\transports\polling-xhr.js:260:18)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      type: 'TransportError',
      description: 400
    }
  },
  event: 'error'
}
{ data: { message: 'BitBns Disconnect' }, event: 'disconnect' }
`

**Comment by atiprashant** [comment]
Please implement a disconnect event at your side to tackle these cases 

https://socket.io/docs/client-api/#Event-%E2%80%98disconnect%E2%80%99
