### ISSUE TITLE
websocket Error

### ISSUE THREAD

**Issue by JoelCode** [bitbns-official/node-bitbns-api#9]
The connection fails quickly and doesn't seem to be able to handle more than 2-3 open socket at the time. The response is just "null"

error: SyntaxError: Unexpected end of JSON input
      at JSON.parse (<anonymous>)
      at Socket.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\src\exchanges\BitBns\BitBns.js:110:29)
      at Socket.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
      at Socket.onevent (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-client\lib\socket.js:278:10)
      at Socket.onpacket (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-client\lib\socket.js:236:12)
      at Manager.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\component-bind\index.js:21:15)
      at Manager.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
      at Manager.ondecoded (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-client\lib\manager.js:345:8)
      at Decoder.<anonymous> (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\component-bind\index.js:21:15)
      at Decoder.Emitter.emit (C:\Users\Joel\WebstormProjects\real-time\coinsy-framework\node_modules\socket.io-parser\node_modules\component-emitter\index.js:133:20)
}

**Comment by atiprashant** [comment]
It has been sorted. Give it a try now
